### ISSUE TITLE
php syntax error

### ISSUE THREAD

**Issue by hp7** [markguinn/silverstripe-email-helpers#12]
Running on PHP 5.3.29
Parse error: syntax error, unexpected '[' in /******/**********/********/**********************.com/**************/vendor/pelago/emogrifier/Classes/Emogrifier.php on line 91

**Comment by markguinn** [comment]
Emogrifier likely only supports php 5.4 now. You could try searching their commit history, finding a version that still supported 5.3 and requiring that specific version in your composer.json. I'd also really encourage you to upgrade to a modern version of php though. This will be a more and more common experience for you.

**Comment by hp7** [comment]
Thx that does seem to be the issue. I switched to 5.4.42 and no error

**Comment by markguinn** [comment]
Glad to hear it!
