### ISSUE TITLE
Expose more config settings of PHPMailer

### ISSUE THREAD

**Issue by bummzack** [markguinn/silverstripe-email-helpers#14]
A lot of Email providers only allow access to their servers with SMTP auth and via SSL. Some even change the default ports.

The following settings of PHPMailer should be exposed via SmtpMailer:
 - `SMTPAuth`
 - `SMTPSecure` should not only allow "tls" but also "ssl"
 - `Port`

**Comment by bummzack** [comment]
Should I create a PR for this?

**Comment by markguinn** [comment]
That would be great.
