### ISSUE TITLE
Could not find package markguinn/silverstripe-email-helpers in a version matching dev-master

### ISSUE THREAD

**Issue by Tijsje** [markguinn/silverstripe-email-helpers#34]
The master branch is not available at Packagist.
Error: 
Your requirements could not be resolved to an installable set of packages.
Problem 1
     - The requested package markguinn/silverstripe-email-helpers dev-master exists as markguinn/silverstripe-email-helpers[1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, dev-bundled-dependencies] but these are rejected by your constraint.
https://packagist.org/packages/markguinn/silverstripe-email-helpers

**Comment by RoyalPulp** [comment]
Please solve this !!!
thx
